image: node:16

stages:
  - lint
  - deploy

dev_lint:
  stage: lint
  only:
    - develop
  script:
    - ls
    - npm i --progress=false
    - npm run lint

pages: # the job must be named pages
  stage: deploy
  script:
    - npm ci
    - npm run build
    - cp -r dist/spa/* dist # copy content of spa to higher hirarchy folder
    - rm -r dist/spa # remove spa folder
    - mv public public-vue # GitLab Pages hooks on the public folder
    - mv dist public # rename the dist folder (result of npm run build)
    # optionally, you can activate gzip support with the following line:
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public # artifact path must be /public for GitLab Pages to pick it up
  only:
    - main
